### ISSUE TITLE
No checkpoint file provided

### ISSUE THREAD

**Issue by havent-invented** [AliRoyat/NTIRE2021-IQA-MACS-Pytorch#1]
Could you please add checkpoint file or link to checkpoint to the repository?
Checkpoint is required for model to work as there are such lines in submission.py:
`
checkpoint = torch.load(rf'{conf_type}\ch_net-best_epoch-389_loss-2.5346076488494873.pth.tar')
net.load_state_dict(checkpoint['model_state_dict'])
`

**Comment by AliRoyat** [comment]
Checkpoint's link can be found [**here**](https://www.dropbox.com/s/r7nhn5wiyhoiboq/ch_net-best_epoch-129.pth.tar?dl=0).
In the current code (pytorch version), the network architecture is not exactly the same as that described in the paper. You can find the same one in the **[Tensorflow version](https://github.com/smehdia/NTIRE2021-IQA-MACS)**.
